//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group4_Invidiual.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Group4_Invidiual.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3530 {
            get {
                object obj = ResourceManager.GetObject("3530", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _45 {
            get {
                object obj = ResourceManager.GetObject("45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _45_30 {
            get {
                object obj = ResourceManager.GetObject("45;30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _45_301 {
            get {
                object obj = ResourceManager.GetObject("45;301", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap burger {
            get {
                object obj = ResourceManager.GetObject("burger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sign_of_the_fork_symbol_is_isolated_on_a_white_background_fork_icon_color_editable_free_vector_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("sign-of-the-fork-symbol-is-isolated-on-a-white-background-fork-icon-color-editabl" +
                        "e-free-vector-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sign_of_the_fork_symbol_is_isolated_on_a_white_background_fork_icon_color_editable_free_vector_removebg_preview__2_ {
            get {
                object obj = ResourceManager.GetObject("sign-of-the-fork-symbol-is-isolated-on-a-white-background-fork-icon-color-editabl" +
                        "e-free-vector-removebg-preview (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sign_of_the_fork_symbol_is_isolated_on_a_white_background_fork_icon_color_editable_free_vector_removebg_preview__3_ {
            get {
                object obj = ResourceManager.GetObject("sign-of-the-fork-symbol-is-isolated-on-a-white-background-fork-icon-color-editabl" +
                        "e-free-vector-removebg-preview (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sign_of_the_fork_symbol_is_isolated_on_a_white_background_fork_icon_color_editable_free_vector_removebg_preview__4_ {
            get {
                object obj = ResourceManager.GetObject("sign-of-the-fork-symbol-is-isolated-on-a-white-background-fork-icon-color-editabl" +
                        "e-free-vector-removebg-preview (4)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sign_of_the_fork_symbol_is_isolated_on_a_white_background_fork_icon_color_editable_free_vector_removebg_preview__5_ {
            get {
                object obj = ResourceManager.GetObject("sign-of-the-fork-symbol-is-isolated-on-a-white-background-fork-icon-color-editabl" +
                        "e-free-vector-removebg-preview (5)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sign_of_the_fork_symbol_is_isolated_on_a_white_background_fork_icon_color_editable_free_vector_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("sign-of-the-fork-symbol-is-isolated-on-a-white-background-fork-icon-color-editabl" +
                        "e-free-vector-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
